In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
wine=datasets.load_wine()

In [4]:
#format the dataset (preloaded dataset from package)
X=wine.data
y=wine.target

In [5]:
#normazlize the datsets
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler().fit(X)

In [6]:
#split the dataset into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=50)

In [7]:
#knn algorithm
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
pred=knn.predict(X_test)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

0.6111111111111112
[[11  2  3]
 [ 1 18  4]
 [ 4  7  4]]
              precision    recall  f1-score   support

           0       0.69      0.69      0.69        16
           1       0.67      0.78      0.72        23
           2       0.36      0.27      0.31        15

    accuracy                           0.61        54
   macro avg       0.57      0.58      0.57        54
weighted avg       0.59      0.61      0.60        54

