In [38]:
from sklearn import datasets,preprocessing,neighbors
from sklearn.datasets import load_iris
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report,confusion_matrix

In [18]:
iris=datasets.load_iris()
print("Iris Data")
print(iris)
print("\n")


Iris Data
{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0

In [19]:
print("iris feature_names")
print("\n")
print(iris.feature_names)
print("\n")

iris feature_names


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']




In [23]:
print("Integers repersenting features(0=setosa,1=versicolor,2=virginica)")
print("\n")

Integers repersenting features(0=setosa,1=versicolor,2=virginica)




In [24]:
print(iris.target)
print("\n")
print("3 classes of target")
print("\n")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


3 classes of target




In [25]:
print(iris.target_names)
print("\n")

['setosa' 'versicolor' 'virginica']




In [26]:
print("total of 150 observations and 4 features")
print("\n")
print(iris.data.shape)
print("\n")

total of 150 observations and 4 features


(150, 4)




In [29]:
X,y=iris.data[:,:], iris.target
X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=y, random_state=0,train_size=0.7)
print("Shape of train and test objects")
print("\n")

Shape of train and test objects




In [36]:
print(X_train.shape)
print(X_test.shape)
print("\n")
print("Shape of new y objects")
print("\n")
print(y_train)
print("\n")
print(y_test)
print("\n")
print(y_train.shape)
print(y_test.shape)
print("\n")
print("Training data before preprocessing")
print(X_train)
print("/n")
scaler=preprocessing.StandardScaler().fit(X_train)
X_train=scaler.transform(X_train)
print("Display scaled data")
print("\n")
print(X_train)
print("\n")
X_test=scaler.transform(X_test)

(105, 4)
(45, 4)


Shape of new y objects


[2 2 2 0 0 0 1 2 1 2 0 1 1 1 0 0 2 1 1 2 2 1 0 0 1 1 0 1 2 2 2 1 2 2 0 0 0
 1 0 0 2 1 2 0 0 0 1 1 0 1 1 1 2 0 1 1 1 1 2 0 1 2 1 1 2 1 2 0 1 2 2 2 2 0
 2 0 0 2 1 0 0 0 0 0 1 2 2 2 0 2 0 0 1 1 1 1 0 2 2 0 2 1 0 2 2]


[2 2 0 0 1 0 1 2 0 1 0 2 0 2 1 2 1 1 1 0 1 2 0 1 2 2 2 2 1 2 1 0 0 1 1 2 1
 0 0 1 0 2 0 0 2]


(105,)
(45,)


Training data before preprocessing
[[6.7 3.3 5.7 2.5]
 [7.7 3.8 6.7 2.2]
 [6.4 3.2 5.3 2.3]
 [4.6 3.6 1.  0.2]
 [5.2 3.4 1.4 0.2]
 [4.4 3.  1.3 0.2]
 [4.9 2.4 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [6.1 3.  4.6 1.4]
 [6.8 3.  5.5 2.1]
 [4.8 3.  1.4 0.3]
 [6.3 3.3 4.7 1.6]
 [5.1 2.5 3.  1.1]
 [6.6 2.9 4.6 1.3]
 [4.9 3.  1.4 0.2]
 [5.  3.4 1.5 0.2]
 [7.7 3.  6.1 2.3]
 [5.6 2.5 3.9 1.1]
 [5.5 2.4 3.8 1.1]
 [6.  2.2 5.  1.5]
 [7.9 3.8 6.4 2. ]
 [5.7 2.9 4.2 1.3]
 [5.  3.6 1.4 0.2]
 [5.4 3.4 1.5 0.4]
 [5.  2.3 3.3 1. ]
 [5.8 2.7 3.9 1.2]
 [5.4 3.9 1.7 0.4]
 [6.1 2.9 4.7 1.4]
 [6.4 3.1 5.5 1.8]
 [6.8 3.2 5.9 2.3]
 [6.7 3.1 5.6 2.4]
 [6.  

In [37]:
score=[]
k_range=range(1,15)
for k in k_range:
    knn=neighbors.KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)
    
print("Predictiion od Species: {}".format(y_pred))
print("Accuracy Score")
print(accuracy_score(y_test,y_pred))
print("confusion matrix")
print(confusion_matrix(y_test,y_pred))
print("Classification Report")
print(classification_report(y_test,y_pred))

Predictiion od Species: [2 2 0 0 1 0 1 1 0 1 0 2 0 2 1 1 1 1 1 0 1 2 0 1 2 2 2 2 1 2 1 0 0 1 1 1 1
 0 0 1 0 2 0 0 2]
Accuracy Score
0.9333333333333333
confusion matrix
[[15  0  0]
 [ 0 15  0]
 [ 0  3 12]]
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.83      1.00      0.91        15
           2       1.00      0.80      0.89        15

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45

