In [8]:
#creating a matrix
import numpy as np
A=np.array([[1,2,4],[2,4,3],[0,1,1]])
B=np.array([[2,-1],[3,2]])
C=np.array([[1,-1,0],[3,1,2],[1,2,5]])
print(A)
print(B)
print(C)

[[1 2 4]
 [2 4 3]
 [0 1 1]]
[[ 2 -1]
 [ 3  2]]
[[ 1 -1  0]
 [ 3  1  2]
 [ 1  2  5]]


In [7]:
#Generate a matrix
A1=np.arange(1,10) #prints 1to9 values as list
print('List: ',A1)
print('After Reshape(3,3)')
A1.reshape(3,3) #reshape(row,colm) it will create MxN Matrix

List:  [1 2 3 4 5 6 7 8 9]
After Reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
#Transpose the Matrix
D=np.array([[3,4,2,8],[1,5,4,7]])
print(D)
# D.transpose() or
print(D.T)

[[3 4 2 8]
 [1 5 4 7]]
[[3 1]
 [4 5]
 [2 4]
 [8 7]]


In [19]:
#Multipy two Matrix
A1=np.arange(1,10).reshape(3,3)
A2=np.arange(5,14).reshape(3,3)
print(A1)
print(A2)
A3= A1*A2
print(A3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[  5  12  21]
 [ 32  45  60]
 [ 77  96 117]]
