In [1]:
import numpy as np
l1 =[2,3,4,5,6]
arr1 = np.array(l1)
print(arr1)

[2 3 4 5 6]


In [4]:
import numpy as np
A = np.array([[10,11,12,13],[21,22,23,24]])
print(A)

[[10 11 12 13]
 [21 22 23 24]]


In [6]:
import numpy as np
arr=np.empty([3,2],dtype=int)
print(arr)

[[ 538976288  811278368]
 [ -23966416        103]
 [ 538976288 1935764768]]


In [7]:
import numpy as np
arr1 = np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [8]:
import numpy as np
arr1 = np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [9]:
import numpy as np
arr1=np.arange(2,7)
print(arr1)


[2 3 4 5 6]


In [10]:
import numpy as np
A=np.array([1,2,3,4,5,6])
B=np.reshape(A,(2,3))
print(B)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np
data = np.array([5,2,7,3,9])
print(data[:])
print(data[1:3])
print(data[:2])
print(data[-2:])

[5 2 7 3 9]
[2 7]
[5 2]
[3 9]


In [16]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[1:2,0:4]
print('b',b)
b=a[1:2,1:2]
print('b',b)
b=a[:2,0:2]
print('b',b)
b=a[1:3,2:4]
print('b',b)

b [[5 6 7 8]]
b [[6]]
b [[1 2]
 [5 6]]
b [[ 7  8]
 [11 12]]


In [22]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[0:2,1:3]
print('1st',b)
b[0,0]=20
print('2nd',b)
print('3rd',a)

1st [[2 3]
 [6 7]]
2nd [[20  3]
 [ 6  7]]
3rd [[ 1 20  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
import numpy as np
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [33]:
import numpy as np
a=np.array([[7,5,9],[2,6,8]])
print('Array a: ',a)
b=np.array([10,10,10])
print('Array b: ',b)
c=np.add(a,b)
print('Addition: ',c)
c=np.multiply(a,b)
print('Multiplication :',c)
c=np.divide(a,b)
print('Divition :',c)

Array a:  [[7 5 9]
 [2 6 8]]
Array b:  [10 10 10]
Addition:  [[17 15 19]
 [12 16 18]]
Multiplication : [[70 50 90]
 [20 60 80]]
Divition : [[0.7 0.5 0.9]
 [0.2 0.6 0.8]]


In [35]:
import numpy as np
arr1=np.ones((3,3),dtype=bool)
print(arr1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [37]:
import numpy as np
x=np.ones((10,10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [39]:
import numpy as np
a=np.array([[7,5,9],[2,6,8]])
print('Array a: ',a)
b=np.array([10,10,10])
print('Array b: ',b)
c=np.add(a,b)
print('Addition: ',c)


Array a:  [[7 5 9]
 [2 6 8]]
Array b:  [10 10 10]
Addition:  [[17 15 19]
 [12 16 18]]


In [53]:
import numpy as np
A=np.array([[7,5],[1,6]])
B=np.array([[5,4],[5,9]])
print(np.concatenate([B],axis=0))
print(np.concatenate([A,A],axis=1))


[[5 4]
 [5 9]]
[[7 5 7 5]
 [1 6 1 6]]


In [55]:
import numpy as np
x=np.array([1,2,3,4])
print(x.sum())
print(x.min())
print(x.max())
print(np.median(x))

10
1
4
2.5


In [58]:
import numpy as np
a=np.array([[1,2],[2,4]])
b=np.array([[7,8]])
c=np.concatenate((a,b),axis=0)
print(c)
print(a.T)

[[1 2]
 [2 4]
 [7 8]]
[[1 2]
 [2 4]]
